# weather.csv - Data Cleaning

In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
df_weather = pd.read_csv("/home/pau/Ironhack/week5/project5/Project-Week-5-Your-Own-Project/your-project/weather.csv")

In [3]:
df_weather.head()

,Date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,...,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events
0,10/13/2014,71,62.0,54,55,51,46,87,68,46,...,29.79,29.65,10,10,4,13,4,21,0.00,Rain
1,10/14/2014,63,59.0,55,52,51,50,88,78,63,...,29.75,29.54,10,9,3,10,5,17,0.11,Rain
2,10/15/2014,62,58.0,54,53,50,46,87,77,67,...,29.71,29.51,10,9,3,18,7,25,0.45,Rain
3,10/16/2014,71,61.0,52,49,46,42,83,61,36,...,29.95,29.81,10,10,10,9,4,-,0.00,Rain
4,10/17/2014,64,60.0,57,55,51,41,87,72,46,...,29.78,29.73,10,10,6,8,3,-,0.14,Rain

In [4]:
df_weather.dtypes

Date                           object
Max_Temperature_F               int64
Mean_Temperature_F            float64
Min_TemperatureF                int64
Max_Dew_Point_F                 int64
MeanDew_Point_F                 int64
Min_Dewpoint_F                  int64
Max_Humidity                    int64
Mean_Humidity                   int64
Min_Humidity                    int64
Max_Sea_Level_Pressure_In     float64
Mean_Sea_Level_Pressure_In    float64
Min_Sea_Level_Pressure_In     float64
Max_Visibility_Miles            int64
Mean_Visibility_Miles           int64
Min_Visibility_Miles            int64
Max_Wind_Speed_MPH              int64
Mean_Wind_Speed_MPH             int64
Max_Gust_Speed_MPH             object
Precipitation_In              float64
Events                         object
dtype: object

In [5]:
df_weather["Date"] = df_weather["Date"].astype("datetime64[ns]")

In [6]:
df_weather.dtypes

Date                          datetime64[ns]
Max_Temperature_F                      int64
Mean_Temperature_F                   float64
Min_TemperatureF                       int64
Max_Dew_Point_F                        int64
MeanDew_Point_F                        int64
Min_Dewpoint_F                         int64
Max_Humidity                           int64
Mean_Humidity                          int64
Min_Humidity                           int64
Max_Sea_Level_Pressure_In            float64
Mean_Sea_Level_Pressure_In           float64
Min_Sea_Level_Pressure_In            float64
Max_Visibility_Miles                   int64
Mean_Visibility_Miles                  int64
Min_Visibility_Miles                   int64
Max_Wind_Speed_MPH                     int64
Mean_Wind_Speed_MPH                    int64
Max_Gust_Speed_MPH                    object
Precipitation_In                     float64
Events                                object
dtype: object

In [7]:
df_weather["Year"] = df_weather["Date"].dt.year

In [9]:
df_weather.head()

,Date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,...,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events,Year
0,2014-10-13,71,62.0,54,55,51,46,87,68,46,...,29.65,10,10,4,13,4,21,0.00,Rain,2014
1,2014-10-14,63,59.0,55,52,51,50,88,78,63,...,29.54,10,9,3,10,5,17,0.11,Rain,2014
2,2014-10-15,62,58.0,54,53,50,46,87,77,67,...,29.51,10,9,3,18,7,25,0.45,Rain,2014
3,2014-10-16,71,61.0,52,49,46,42,83,61,36,...,29.81,10,10,10,9,4,-,0.00,Rain,2014
4,2014-10-17,64,60.0,57,55,51,41,87,72,46,...,29.73,10,10,6,8,3,-,0.14,Rain,2014